name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? (Actual vs Expected Behavior)
      description: Please describe what happened and what you expected to happen.
      placeholder: Provide a clear description of the actual behavior and the expected outcome.
    validations:
      required: true

  - type: textarea
    id: icon-mods
    attributes:
      label: What mods for icons where you using, if any?
      description: List the mods you used for custom icons.
      placeholder: Aura's Inventory Tweaks, Kome's Inventory Tweaks, ...

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps so we can reproduce the issue.
      placeholder: List the steps required to reproduce the bug.
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What mod version were you using?
      options:
        - 1.0.0
        - 1.1.0
        - 1.2.0
        - 2.0.0
        - 3.0.0
      default: 0
    validations:
      required: true

  - type: input
    id: Skyrim-Version
    attributes:
      label: What Skyrim version are you using?
      description: Specify the Skyrim version number here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (Expandable)
      description: Please paste any relevant log output here. This field is expandable for better readability and will be automatically formatted as shell code.
      render: shell
      placeholder: Paste your logs here.   

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../blob/master/CONDUCT).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
